// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller

import { application } from "./application"

import ItemShowController from "./itemShow_controller.js"
application.register("itemShow", ItemShowController)

import ItemTypeController from "./itemType_controller.js"
application.register("itemType", ItemTypeController)

import MapsController from "./maps_controller.js"
application.register("maps", MapsController)

import SearchController from "./search_controller.js"
application.register("search", SearchController)

import TradeController from "./trade_controller.js"
application.register("trade", TradeController)

import UserMapController from "./userMap_controller.js"
application.register("userMap", UserMapController)
