// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller

// import { application } from "./application"

// import HelloController from "./hello_controller"
// application.register("hello", HelloController)

import { Application } from "@hotwired/stimulus"
import { definitionsFromContext } from "@hotwired/stimulus-webpack-helpers"

window.Stimulus = Application.start()
const context = require.context("../controllers", true, /\.js$/)
Stimulus.load(definitionsFromContext(context))

window.dispatchMapsEvent = function (...args) {
  const event = document.createEvent("Events")
  event.initEvent("google-maps-callback", true, true)
  event.args = args
  window.dispatchEvent(event)
}